import { FC } from 'react'
import type { Metadata } from 'next'
import { ThemeProvider } from '@mui/material/styles'

import '@/infrastructure/ui/styles/globals.css'

import { HOCCtr } from '@/infrastructure/ui/components'
import { ProviderRedux, StyledComponentsRegistry } from '@/infrastructure/ui/lib'
import { themeMUI } from '@/infrastructure/ui/styles/Theme'

export const metadata: Metadata = {
    title: 'Hugo Andres Diaz Bernal´s Portfolio',
    description: 'Generated by Hugo Andres Diaz Bernal',
}

export interface IRootLayout {
    children: React.ReactNode
}

const RootLayout: FC<IRootLayout> = ({ children }) => {
    return (
        <ProviderRedux>
            <StyledComponentsRegistry>
                <ThemeProvider theme={themeMUI}>
                    <HOCCtr>{children}</HOCCtr>
                </ThemeProvider>
            </StyledComponentsRegistry>
        </ProviderRedux>
    )
}

export default RootLayout
