import type { Metadata } from 'next';
import { FC } from 'react';

export const metadata: Metadata = {
	title: 'Portfolio Hugo Andres Diaz Bernal',
	description: 'Generated by Hugo Andres Diaz Bernal',
};

export interface Readonly {
	children: React.ReactNode;
}

const RootLayout: FC<Readonly> = ({ children }) => {
	return (
		<html lang='en'>
			<body>{children}</body>
		</html>
	);
};

export default RootLayout;
