import { FC } from 'react'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

import '@/infrastructure/ui/styles/globals.css'

import { FullCtr } from '@/infrastructure/ui/components'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Hugo Andres Diaz Bernal´s Portfolio',
    description: 'Generated by Hugo Andres Diaz Bernal',
}

export interface IRootLayout {
    children: React.ReactNode
}

const RootLayout: FC<IRootLayout> = ({ children }) => {
    return (
        <html lang="en">
            <body className={montserrat.className}>
                <FullCtr>{children}</FullCtr>
            </body>
        </html>
    )
}

export default RootLayout
