import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
    title: 'Hugo Andres Diaz Bernal´s Portfolio',
    description: 'Generated by Hugo Andres Diaz Bernal',
}

const NotFound = (): JSX.Element => {
    return <div>Error 404</div>
}

export default NotFound
