import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Hugo Andres Diaz Bernal´s Portfolio',
    description: 'Generated by Hugo Andres Diaz Bernal',
}

const HomePage = () => {
    return (
        <main className="min-h-screen flex flex-col justify-center items-center">
            <h1>This site is under construction</h1>
        </main>
    )
}

export default HomePage
