import { HomeView } from '@/infrastructure/ui/modules/HomeModule'
import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Hugo Andres Diaz Bernal´s Portfolio',
    description: 'Generated by Hugo Andres Diaz Bernal',
}

const HomePage = (): JSX.Element => {
    return <HomeView />
}

export default HomePage
