import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Hugo Andres Diaz Bernal´s Portfolio',
    description: 'Generated by Hugo Andres Diaz Bernal',
}

const ContentPage = () => {
    return <div>ContentPage</div>
}

export default ContentPage
