import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
    title: 'Hugo Andres Diaz Bernal´s Portfolio',
    description: 'Generated by Hugo Andres Diaz Bernal',
}

const RegisterPage = (): JSX.Element => {
    return <div>RegisterPage</div>
}

export default RegisterPage
