import React from 'react'
import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Hugo Andres Diaz Bernal´s Portfolio',
    description: 'Generated by Hugo Andres Diaz Bernal',
}

const AdminHomePage = (): JSX.Element => {
    return <div>AdminHomePage</div>
}

export default AdminHomePage
